name: note
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  get: 4.6.5
  firebase_auth: 4.6.3
  cloud_firestore: 4.8.1
  lottie: 2.3.2
  http: 0.13.0
  google_fonts: 4.0.0
  intl: 0.18.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

